apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend
        image: docker.io/dancb10/backend
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  type: NodePort
  ports:
   - port: 9090
  selector:
   app: backend1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend
        image: docker.io/dancb10/backend
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  type: NodePort
  ports:
   - port: 9090
  selector:
   app: backend2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend3
  labels:
    app: backend3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend3
  template:
    metadata:
      labels:
        app: backend3
    spec:
      containers:
      - name: backend
        image: docker.io/dancb10/backend
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend3
  labels:
    app: backend3
spec:
  type: NodePort
  ports:
   - port: 9090
  selector:
   app: backend3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend4
  labels:
    app: backend4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend4
  template:
    metadata:
      labels:
        app: backend4
    spec:
      containers:
      - name: backend
        image: docker.io/dancb10/backend
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend4
  labels:
    app: backend4
spec:
  type: NodePort
  ports:
   - port: 9090
  selector:
   app: backend4
